#!/usr/bin/env bash
set -eou pipefail

help() {
  echo "Usage: ./zip [plugin]"
  echo -e "Plugins:\n  template - Template System\n  loops - Loops & Logic"
}

main() {

  local org=tangibleinc
  local repo=template-system
  local branch=main
  local zipfile=tangible-template-system.zip

  if [ -z "$*" ]; then
    help
    exit
  fi

  mkdir -p vendor

  for arg in "$@"
  do
    case "$arg" in
      template)
        echo "Template System"
        cd vendor

        if [ -d "$repo" ]; then
          rm -rf "$repo"
        fi
        curl -sL https://github.com/$org/$repo/archive/refs/heads/$branch.tar.gz | tar xz
        mv "${repo}-${branch}" "$repo"

        if [ -f "$zipfile" ]; then
          rm "$zipfile"
        fi
        zip -r "$zipfile" "$repo"
        mv "$zipfile" ../plugins/tangible-template-system.zip
        cd ..
        echo "Created: $zipfile"
      ;;

      loops)
        echo "Loops & Logic"
        cd vendor
        zipfile=tangible-loops-and-logic.zip
        local latest=tangible-loops-and-logic-latest.zip
        curl -LO https://bitbucket.org/tangibleinc/loops-and-logic/downloads/"$latest"
        mv "$latest" ../plugins/"$zipfile"
        cd ..
        echo "Created: $zipfile"
      ;;

      *)
        help
      ;;
    esac
  done
}

main "$@"
